# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='id',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='issuekey',
            field=models.CharField(default='Issuekey', max_length=32, primary_key=True, serialize=False),
        ),
    ]
