# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0002_auto_20180407_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('Issuekey', models.CharField(default='Issuekey', max_length=32, primary_key=True, serialize=False)),
                ('Summary', models.TextField()),
                ('Description', models.TextField()),
                ('Project', models.CharField(max_length=32)),
                ('Component', models.CharField(max_length=32)),
                ('Reporter', models.CharField(max_length=32)),
                ('Priority', models.CharField(max_length=32)),
                ('Linkedissue', models.CharField(max_length=32)),
                ('location_result_list', models.TextField()),
                ('method_result_list', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='recommendation',
        ),
    ]
