# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0003_auto_20180415_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Url',
            field=models.URLField(null=True),
        ),
    ]
