# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0004_issue_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='Url',
        ),
    ]
