# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0005_remove_issue_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Component',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AlterField(
            model_name='issue',
            name='Linkedissue',
            field=models.CharField(default='null', max_length=32),
        ),
    ]
