# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0006_auto_20180415_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Description',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='Summary',
            field=models.TextField(default='null'),
        ),
    ]
