# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0007_auto_20180415_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('Name', models.CharField(default='Issuekey', max_length=32, primary_key=True, serialize=False)),
                ('Description', models.TextField(default='null')),
                ('Parameters', models.CharField(default='( )', max_length=32)),
                ('ModifierType', models.CharField(default='void', max_length=32)),
                ('Url', models.URLField(null=True)),
            ],
        ),
    ]
