# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0008_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='similar_issues_list',
            field=models.TextField(default=''),
        ),
    ]
