# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0009_issue_similar_issues_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('Name', models.CharField(default='Issuekey', max_length=32, primary_key=True, serialize=False)),
                ('Dir', models.CharField(default='', max_length=128)),
                ('Description', models.TextField(default='null')),
                ('Project', models.CharField(max_length=32)),
            ],
        ),
    ]
