# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0010_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='Dir',
            field=models.CharField(default='Dir', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='Name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
