# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0011_auto_20180418_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Method_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='Variables_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='Variables_name',
            field=models.TextField(default=''),
        ),
    ]
