# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0012_auto_20180418_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Status',
            field=models.CharField(default='closed', max_length=16),
        ),
    ]
