# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-18 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0014_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='Example',
            field=models.TextField(default='null'),
        ),
    ]
